### ISSUE TITLE
sign plugin by npx failed on Ubuntu 20.04

### ISSUE THREAD

**Issue by sangshuduo** [grafana/grafana-plugin-repository#811]
$ nodejs --version
v10.19.0
$ npm --version
6.14.4
$ npx --version
6.14.4
$ yarn --version
0.32+git

$ npx @grafana/toolkit plugin:sign
  Building manifest...
  TypeError: fs_1.default.promises.opendir is not a function
      at /home/shuduo/.npm/_npx/18445/lib/node_modules/@grafana/toolkit/src/plugins/manifest.js:17:80
      at step (/home/shuduo/.npm/_npx/18445/lib/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:140:27)
      at Object.next (/home/shuduo/.npm/_npx/18445/lib/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:121:57)
      at resume (/home/shuduo/.npm/_npx/18445/lib/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:210:48)
      at /home/shuduo/.npm/_npx/18445/lib/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:209:125
      at new Promise (<anonymous>)
      at Object.i.(anonymous function) [as next] (/home/shuduo/.npm/_npx/18445/lib/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:209:67)
      at Object.<anonymous> (/home/shuduo/.npm/_npx/18445/lib/node_modules/@grafana/toolkit/src/plugins/manifest.js:94:49)
      at step (/home/shuduo/.npm/_npx/18445/lib/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:140:27)
      at Object.next (/home/shuduo/.npm/_npx/18445/lib/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:121:57)
      at fulfilled (/home/shuduo/.npm/_npx/18445/lib/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:111:62)
      at process._tickCallback (internal/process/next_tick.js:68:7)
      at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
      at findNodeScript.then.existing (/usr/share/nodejs/libnpx/index.js:268:14)

**Comment by sergejmueller** [comment]
@sangshuduo I think, you need Node.JS >= 12.20, better 14 or 15.

**Comment by sangshuduo** [comment]
@sergejmueller thanks, already solved it with 15.
