### ISSUE TITLE
quicklog-panel-plugin

### ISSUE THREAD

**Issue by ui3o** [grafana/grafana-plugin-repository#974]
Hi!

I made a new panel plugin. I would like to share with grafana community. I cloned this repository: https://github.com/marcusolsson/grafana-hexmap-panel

When a create new tag (release) my signature flow fails. Here is what I got: https://github.com/ui3o/grafana-quick-log-panel/runs/2833780981?check_suite_focus=true#step:13:12
```
Run yarn sign
yarn run v1.22.10
$ grafana-toolkit plugin:sign
  Building manifest...
  Signing manifest...
  Error: Error signing manifest: Field is required: rootUrls
      at Object.<anonymous> (/home/runner/work/grafana-quick-log-panel/grafana-quick-log-panel/node_modules/@grafana/toolkit/src/plugins/manifest.js:165:31)
      at step (/home/runner/work/grafana-quick-log-panel/grafana-quick-log-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:140:27)
      at Object.throw (/home/runner/work/grafana-quick-log-panel/grafana-quick-log-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:121:57)
      at rejected (/home/runner/work/grafana-quick-log-panel/grafana-quick-log-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:112:69)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
Done in 1.32s.
```
I read this: https://grafana.com/docs/grafana/latest/administration/configuration/#root_url
I know if I want to use it on private server how it possible, but what do I need to do if I want to share? 

Please help me to finish my flow. I hope I can give it to the community soon. 

Thank you!

**Comment by marcusolsson** [comment]
To share your plugin, you need to submit it for review. Once the plugin has been reviewed by a Grafana team members, they'll assign a signature level to you plugin so that you can generate a public plugin signature.

For more information on how to submit your plugin, refer to the README:

https://github.com/grafana/grafana-plugin-repository#grafana-plugin-repository
